# Generated by Django 4.2.7 on 2023-11-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
