# Generated by Django 4.2.7 on 2023-11-08 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notes_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='created',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='modified',
        ),
    ]
